from queueDC import *

def main():
    m = int(input("Give me a capacity:"))
    #a = dynamicCircular(m)
    #a.addToFront(1)
    #.addToFront(2)
    #a.addToFront(3)
    #a.addToFront(4)
    #a.addToFront(5)
    #a.addToFront(6)
    #a.display()
    #a.removeFront()
    #a.removeFront()
    #a.removeFront()
    #a.removeFront()
    #a.removeFront()
    #a.removeFront()
    #a.display()
    #a.addToBack(1)
    #a.addToBack(2)
    #a.addToBack(3)
    #a.addToBack(4)
    #a.addToBack(5)
    #a.addToBack(6)
    #a.display()
    #a.removeBack()
    #a.removeBack()
    #a.removeBack()
    #a.removeBack()
    #a.removeBack()
    #a.removeBack()
    #a.display()
    #print(a.toArray())
    print('Start of Queue')
    a = QueueDC(m)
    a.enqueue(1)
    a.enqueue(2)
    a.enqueue(3)
    a.enqueue(4)
    a.enqueue(5)
    a.enqueue(6)
    print(a.isEmpty())
    a.store.display()
    a.dequeue()
    a.dequeue()
    a.dequeue()
    a.dequeue()
    a.dequeue()
    a.dequeue()
    a.store.display()
    a.enqueue(1)
    a.enqueue(2)
    a.enqueue(3)
    a.enqueue(4)
    a.enqueue(5)
    a.enqueue(6)
    a.store.display()
    a.dequeue()
    a.dequeue()
    a.dequeue()
    a.dequeue()
    a.dequeue()
    a.dequeue()
    a.store.display()
    print(a.isEmpty())
    return

main()

