from stack import *

def main():
    #a = singlyLinkedList()
    #print('Added 7 values')
    #a.addToFront(1)
    #a.addToFront(2)
    #a.addToFront(3)
    #a.addToFront(4)
    #a.addToFront(5)
    #a.addToFront(6)
    #a.addToFront(7)
    #a.display()
    #print('Removed 4 values from back')
    #a.removeBack()
    #a.removeBack()
    #a.removeBack()
    #a.display()
    #print('Add 3 values to Back')
    #a.addToBack(1)
    #a.addToBack(2)
    #a.addToBack(3)
    #a.display()
    #print('Removed 4 values from Front')
    #a.removeFront()
    #a.removeFront()
    #a.removeFront()
    #a.removeFront()
    #a.display()
    print('This is the SinglyLinkedList:')
    a = stackSingly()
    a.push(1)
    a.push(2)
    a.push(3)
    a.push(4)
    a.push(5)
    a.push(6)
    a.push(7)
    a.store.display()
    print('Pop')
    a.pop()
    a.pop()
    a.pop()
    a.pop()
    a.pop()
    a.store.display()
    print('This size is: ', a.size())
    #a.size

main()
 
